version: '3.8'

services:
  fastapi:
    build: .
    volumes:
      - ./:/myapp/
    ports:
      - 8000:8080  # Maps host port 8000 to container port 8080
    networks:
      - app-network
    restart: always

networks:
  app-network:
