name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.12] # Define Python versions here
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests with Pytest
        run: pytest

  build-and-push-docker-main:
    needs: test
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: joec11/is690_midterm:push-${{ github.run_number }}-${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=joec11/is690_midterm:cache
          cache-to: type=inline,mode=max
          
      - name: Scan the Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: joec11/is690_midterm:push-${{ github.run_number }}-${{ github.ref_name }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  build-and-push-docker-pr-main:
    needs: test
    if: github.event_name == 'pull_request' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image for PR
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: joec11/is690_midterm:pr-${{ github.event.pull_request.number }}-${{ github.run_number }}-${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=joec11/is690_midterm:cache
          cache-to: type=inline,mode=max
          
      - name: Scan the Docker image for PR
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: joec11/is690_midterm:pr-${{ github.event.pull_request.number }}-${{ github.run_number }}-${{ github.ref_name }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

  build-and-push-docker-pr-not-main:
    needs: test
    if: github.event_name == 'pull_request' && github.ref_name != 'main' && github.head_ref != 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image for PR
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: joec11/is690_midterm:pr-${{ github.event.pull_request.number }}-${{ github.run_number }}-${{ github.head_ref }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=joec11/is690_midterm:cache
          cache-to: type=inline,mode=max
          
      - name: Scan the Docker image for PR
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: joec11/is690_midterm:pr-${{ github.event.pull_request.number }}-${{ github.run_number }}-${{ github.head_ref }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
